### ISSUE TITLE
[Model Catalog UI] Do not use URI fragments, use label instead

### ISSUE THREAD

**Issue by dgarijo** [mintproject/model-catalog-explorer#17]
See for example inputs/outputs of: 
https://models.mint.isi.edu/models/explore/SWAT/bb777f26-004d-4342-82de-88de532eb6ce/c56c4034-126a-4ec3-a861-ea2857ce65e1

The system is using the URI fragments, which are not great because they have been created automatically. Instead, the label should be used.

**Comment by hvarg** [comment]
Fixed on last update
